import {randomUUID} from "crypto"
import {type NextRequest,NextResponse} from "next/server"
import {requireTenantAdmin,adminUserIdPerDatabase,accessErrorStatus} from "@/lib/auth/admin-access"
import {createServiceClient} from "@/lib/supabase/server"
import {isModuleActive} from "@/lib/modules"
const BUCKET="hr-private",MAX=15*1024*1024,types=new Set(["application/pdf","image/jpeg","image/png","application/vnd.openxmlformats-officedocument.wordprocessingml.document"])
async function ctx(req:NextRequest){const i=await requireTenantAdmin(req);const db=createServiceClient();if(!await isModuleActive(db,i.propertyId,"hr"))throw new Error("module_disabled");return {i,db}}
export async function GET(req:NextRequest){try{const {i,db}=await ctx(req);const employee=req.nextUrl.searchParams.get("employee_id");let q=db.from("hr_documents").select("id,employee_id,category,title,period_month,expires_on,original_name,mime_type,size_bytes,visible_to_employee,created_at").eq("property_id",i.propertyId).order("created_at",{ascending:false}).limit(250);if(employee)q=q.eq("employee_id",employee);const r=await q;if(r.error)throw r.error;return NextResponse.json({documents:r.data||[]})}catch(e){return NextResponse.json({error:"documents_load_failed"},{status:accessErrorStatus(e)})}}
export async function POST(req:NextRequest){try{const {i,db}=await ctx(req);const f=await req.formData(),file=f.get("file"),employee_id=String(f.get("employee_id")||""),category=String(f.get("category")||"other"),title=String(f.get("title")||"").trim().slice(0,160),period=String(f.get("period_month")||"")||null,expires=String(f.get("expires_on")||"")||null;if(!(file instanceof File)||!types.has(file.type)||file.size<=0||file.size>MAX||!employee_id||!title||!["payslip","contract","certificate","policy","other"].includes(category))return NextResponse.json({error:"invalid_document"},{status:400});const emp=await db.from("hr_employees").select("id").eq("id",employee_id).eq("property_id",i.propertyId).maybeSingle();if(!emp.data)return NextResponse.json({error:"employee_not_found"},{status:404});const ext=file.name.split(".").pop()?.replace(/[^a-z0-9]/gi,"").slice(0,8)||"bin",path=`${i.propertyId}/${employee_id}/${randomUUID()}.${ext}`;const up=await db.storage.from(BUCKET).upload(path,Buffer.from(await file.arrayBuffer()),{contentType:file.type,upsert:false});if(up.error)throw up.error;const ins=await db.from("hr_documents").insert({property_id:i.propertyId,employee_id,category,title,period_month:period?`${period}-01`:null,expires_on:expires,storage_path:path,original_name:file.name.slice(0,255),mime_type:file.type,size_bytes:file.size,uploaded_by:adminUserIdPerDatabase(i.adminUserId)}).select().single();if(ins.error){await db.storage.from(BUCKET).remove([path]);throw ins.error}await db.from("hr_audit_log").insert({property_id:i.propertyId,actor_admin_user_id:adminUserIdPerDatabase(i.adminUserId),employee_id,action:"document_uploaded",entity_type:"document",entity_id:ins.data.id,metadata:{category}});return NextResponse.json(ins.data,{status:201})}catch(e){console.error("[hr] document upload",e);return NextResponse.json({error:"document_upload_failed"},{status:accessErrorStatus(e)})}}

