"use client"
import {useCallback,useEffect,useState} from "react"
import {format} from "date-fns"
import {it} from "date-fns/locale"
import {AdminHeader} from "@/components/admin/admin-header"
import {Button} from "@/components/ui/button"
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card"
import {Badge} from "@/components/ui/badge"
import {Input} from "@/components/ui/input"
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select"
type Shift={id:string;starts_at:string;ends_at:string;location:string|null;response_status:string};type Leave={id:string;kind:string;starts_on:string;ends_on:string;status:string}
export default function Page(){const[shifts,setShifts]=useState<Shift[]>([]),[leaves,setLeaves]=useState<Leave[]>([]),[error,setError]=useState("");const today=new Date().toISOString().slice(0,10);const[form,setForm]=useState({kind:"holiday",starts_on:today,ends_on:today});const load=useCallback(async()=>{const r=await fetch("/api/hr/me"),d=await r.json();if(!r.ok)throw new Error(d.error);setShifts(d.shifts);setLeaves(d.leave_requests)},[]);useEffect(()=>{load().catch(e=>setError(e.message==="employee_not_linked"?"Il tuo account non è ancora collegato a una scheda dipendente.":"Caricamento non riuscito."))},[load]);async function post(body:object){const r=await fetch("/api/hr/me",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(r.ok)await load();else setError("Operazione non riuscita.")}
return <div className="min-h-screen bg-background"><AdminHeader title="I miei turni" subtitle="Turni pubblicati, conferme e richieste di assenza"/><main className="mx-auto grid max-w-5xl gap-6 px-4 py-8 md:grid-cols-2">{error&&<div className="md:col-span-2 rounded border p-3 text-sm">{error}</div>}<Card><CardHeader><CardTitle>Prossimi turni</CardTitle></CardHeader><CardContent className="space-y-3">{shifts.map(s=><div key={s.id} className="rounded-lg border p-3"><div className="font-medium capitalize">{format(new Date(s.starts_at),"EEEE d MMMM",{locale:it})}</div><div className="text-sm">{format(new Date(s.starts_at),"HH:mm")}–{format(new Date(s.ends_at),"HH:mm")} {s.location&&`· ${s.location}`}</div><div className="mt-2 flex items-center gap-2"><Badge variant="outline">{s.response_status}</Badge>{s.response_status==="pending"&&<><Button size="sm" onClick={()=>post({action:"respond",shift_id:s.id,response:"confirmed"})}>Confermo</Button><Button size="sm" variant="outline" onClick={()=>post({action:"respond",shift_id:s.id,response:"declined"})}>Non posso</Button></>}</div></div>)}{!shifts.length&&<p className="text-sm text-muted-foreground">Nessun turno pubblicato.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Richiedi assenza</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={form.kind} onValueChange={v=>setForm({...form,kind:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="holiday">Ferie</SelectItem><SelectItem value="permission">Permesso</SelectItem><SelectItem value="rol">ROL</SelectItem><SelectItem value="sickness">Malattia</SelectItem><SelectItem value="unavailability">Indisponibilità</SelectItem></SelectContent></Select><div className="grid grid-cols-2 gap-2"><Input type="date" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/><Input type="date" value={form.ends_on} onChange={e=>setForm({...form,ends_on:e.target.value})}/></div><Button onClick={()=>post({action:"leave",...form})}>Invia richiesta</Button><div className="space-y-2 pt-3">{leaves.map(l=><div key={l.id} className="flex justify-between rounded border p-2 text-sm"><span>{l.starts_on}–{l.ends_on}</span><Badge variant="outline">{l.status}</Badge></div>)}</div></CardContent></Card></main></div>}
