import {
  Activity,
  BarChart3,
  Gauge,
  Boxes,
  Building2,
  CalendarClock,
  Coins,
  CreditCard,
  Database,
  FileText,
  Globe,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  LayoutDashboard,
  ListTodo,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  PhoneCall,
  Radio,
  Scale,
  Settings,
  Sparkles,
  Star,
  Tag,
  UserPlus,
  Users,
} from "lucide-react"

export type NavPlacement = "operative" | "settings" | "platform"

export interface NavEntry {
  id: string
  href: string
  label: string
  description: string
  placement: NavPlacement
  icon: React.ComponentType<{ className?: string }>
  primary?: boolean
  module?: string
  strictModule?: boolean
  area?: string
  adminOnly?: boolean
  platformOnly?: boolean
  requiresPermission?: "can_manage_users"
  match?: (pathname: string) => boolean
}

export const NAV_ENTRIES: NavEntry[] = [
  {
    id: "dashboard",
    href: "/admin/dashboard",
    label: "Dashboard",
    description: "Sintesi della struttura: conversazioni, chiamate e attivita' recenti",
    placement: "operative",
    icon: LayoutDashboard,
    primary: true,
  },
  {
    id: "inbox",
    href: "/admin/inbox",
    label: "Inbox",
    description: "Tutte le conversazioni dei canali in un'unica casella condivisa",
    placement: "operative",
    icon: Inbox,
    module: "inbox",
    primary: true,
  },
  {
    id: "reviews",
    href: "/admin/reviews",
    label: "Recensioni",
    description: "Leggi le recensioni della struttura e trasforma le criticita' in attivita' operative",
    placement: "operative",
    icon: Star,
    module: "reviews",
    adminOnly: true,
    primary: true,
  },
  {
    id: "crm",
    href: "/admin/crm",
    label: "CRM",
    description: "Contatti, richieste e storico dei rapporti con gli ospiti",
    placement: "operative",
    icon: Users,
    match: (p) => p.startsWith("/admin/crm"),
    module: "crm",
    area: "crm",
    primary: true,
  },
  {
    id: "calls",
    href: "/admin/calls",
    label: "Telefonate",
    description: "Registro delle chiamate del centralino, comprese quelle perse",
    placement: "operative",
    icon: PhoneCall,
    module: "inbox",
    area: "calls",
    primary: true,
  },
  {
    id: "operator-performance",
    href: "/admin/operator-performance",
    label: "Performance operatori",
    description: "Quante risposte manda ciascuno e quanto attende chi scrive",
    placement: "operative",
    icon: Gauge,
    adminOnly: true,
  },
  {
    id: "marketing",
    href: "/admin/marketing",
    label: "Marketing",
    description: "Email Marketing e Smart Ads Google, Meta e TikTok",
    placement: "operative",
    icon: Megaphone,
    match: (p) => p.startsWith("/admin/marketing"),
    area: "marketing",
    primary: true,
  },
  {
    id: "my-work",
    href: "/admin/my-work",
    label: "I miei turni",
    description: "I tuoi turni assegnati, da confermare o segnalare",
    placement: "operative",
    icon: CalendarClock,
    module: "hr",
  },
  {
    id: "hr",
    href: "/admin/hr",
    label: "Personale e turni",
    description: "Dipendenti, tabellone dei turni, assenze e pubblicazione",
    placement: "operative",
    icon: CalendarClock,
    module: "hr",
    area: "hr",
    adminOnly: true,
  },
  {
    id: "todos",
    href: "/admin/todos",
    label: "Todos",
    description: "Attivita' da svolgere assegnate al personale",
    placement: "operative",
    icon: ListTodo,
    area: "todos",
  },
  {
    id: "suite-hotelprofitai",
    href: "/api/platform/suite-launch?product=hotelprofitai",
    label: "Controllo di gestione",
    description: "Apri HotelProfitAI senza un nuovo login",
    placement: "operative",
    icon: Coins,
    module: "hotelprofitai",
    strictModule: true,
  },
  {
    id: "suite-santaddeo",
    href: "/api/platform/suite-launch?product=santaddeo",
    label: "Revenue & pricing",
    description: "Apri Santaddeo senza un nuovo login",
    placement: "operative",
    icon: BarChart3,
    module: "santaddeo",
    strictModule: true,
  },
  {
    id: "suite-manubot",
    href: "/api/platform/suite-launch?product=manubot",
    label: "Gestione manutenzioni",
    description: "Apri ManuBot senza un nuovo login",
    placement: "operative",
    icon: ListTodo,
    module: "manubot",
    strictModule: true,
  },
  {
    id: "tracking-visitors",
    href: "/admin/tracking/visitors",
    label: "Visitatori",
    description: "Sessioni in corso sul sito e cronologia degli eventi",
    placement: "operative",
    icon: BarChart3,
    module: "tracking",
    area: "tracking",
  },
  {
    id: "tracking-demand",
    href: "/admin/tracking/demand",
    label: "Calendario domanda",
    description: "Le date piu' cercate dai potenziali ospiti, giorno per giorno",
    placement: "operative",
    icon: CalendarClock,
    module: "tracking",
    area: "tracking",
  },
  {
    id: "monitoring",
    href: "/admin/monitoring",
    label: "Monitoring",
    description: "Stato del sistema e segnalazioni da tenere d'occhio",
    placement: "operative",
    icon: Activity,
    area: "monitoring",
  },
  {
    id: "channels",
    href: "/admin/channels",
    label: "Canali",
    description: "Email, WhatsApp, Telegram, Chat e Telefono IP",
    placement: "settings",
    icon: Radio,
    match: (p) => p.startsWith("/admin/channels"),
    module: "inbox",
  },
  {
    id: "knowledge",
    href: "/admin/knowledge",
    label: "Assistente IA",
    description: "Basi di conoscenza, comportamento e domande da approvare",
    placement: "settings",
    icon: Sparkles,
    match: (p) => p.startsWith("/admin/knowledge"),
    module: "inbox",
    adminOnly: true,
  },
  {
    id: "cms",
    href: "/admin/cms/studio",
    label: "CMS",
    description: "Crea il sito con template, chat guidata e gestione pagine",
    placement: "settings",
    icon: FileText,
    match: (p) => p.startsWith("/admin/cms"),
    module: "cms",
    area: "cms",
  },
  {
    id: "message-rules",
    href: "/admin/message-rules",
    label: "Regole Messaggi",
    description: "Configura messaggi automatici basati sul comportamento",
    placement: "settings",
    icon: MessageSquare,
    module: "inbox",
    area: "message-rules",
  },
  {
    id: "photos",
    href: "/admin/photos",
    label: "Foto",
    description: "Carica e organizza le foto della struttura",
    placement: "settings",
    icon: ImageIcon,
    area: "photos",
  },
  {
    id: "gallery",
    href: "/admin/gallery",
    label: "Gallery",
    description: "Composizione delle gallerie mostrate sul sito",
    placement: "settings",
    icon: ImageIcon,
    area: "gallery",
  },
  {
    id: "categories",
    href: "/admin/categories",
    label: "Categorie",
    description: "Categorie con cui si classificano le foto",
    placement: "settings",
    icon: Tag,
    area: "categories",
  },
  {
    id: "tracking-sites",
    href: "/admin/tracking/sites",
    label: "Tracking & Siti",
    description: "Chiavi di tracking e domini autorizzati dei siti",
    placement: "settings",
    icon: BarChart3,
    module: "tracking",
    area: "tracking",
  },
  {
    id: "analytics-sources",
    href: "/admin/settings/analytics-sources",
    label: "Sorgenti statistiche",
    description: "Caselle e canali che contano nei numeri del cruscotto",
    placement: "settings",
    icon: BarChart3,
    area: "tracking",
  },
  {
    id: "reviews-settings",
    href: "/admin/settings/reviews",
    label: "Configurazione recensioni",
    description: "Configura le fonti del modulo Recensioni condiviso nella suite 4BID",
    placement: "settings",
    icon: Star,
    module: "reviews",
    adminOnly: true,
  },
  {
    id: "embed-scripts",
    href: "/admin/embed-scripts",
    label: "Embed scripts",
    description: "Script da incorporare nei siti della struttura",
    placement: "settings",
    icon: Mail,
    area: "embed-scripts",
  },
  {
    id: "domains",
    href: "/admin/settings/domains",
    label: "Domini",
    description: "Sottodominio e dominio personalizzato della struttura",
    placement: "settings",
    icon: Globe,
    adminOnly: true,
  },
  {
    id: "site-legal",
    href: "/admin/settings/site-legal",
    label: "Dati legali e policy",
    description: "Footer societario, Privacy Policy, Cookie Policy e White Label",
    placement: "settings",
    icon: Scale,
    adminOnly: true,
  },
  {
    id: "api-access",
    href: "/admin/settings/api-access",
    label: "Accesso API",
    description: "Token con cui un sistema esterno legge i dati della struttura",
    placement: "settings",
    icon: KeyRound,
    adminOnly: true,
  },
  {
    id: "operator-rewards",
    href: "/admin/settings/rewards",
    label: "Premi sugli obiettivi",
    description: "Configura premi in punti o denaro collegati agli obiettivi degli operatori",
    placement: "settings",
    icon: Coins,
    adminOnly: true,
  },
  {
    id: "hr-settings",
    href: "/admin/settings/hr",
    label: "HR · Timbratura e posizione",
    description: "Configura sede, raggio e regole GPS della timbratura",
    placement: "settings",
    icon: CalendarClock,
    module: "hr",
    adminOnly: true,
  },
  {
    id: "users",
    href: "/admin/users",
    label: "Gestione Utenti",
    description: "Utenti, ruoli e aree visibili a ciascuno",
    placement: "settings",
    icon: Users,
    match: (p) => p.startsWith("/admin/users"),
    adminOnly: true,
    requiresPermission: "can_manage_users",
  },
  {
    id: "modules",
    href: "/admin/modules",
    label: "Moduli",
    description: "Attiva e gestisci i moduli della piattaforma",
    placement: "settings",
    icon: Boxes,
    match: (p) => p.startsWith("/admin/modules"),
    adminOnly: true,
  },
  {
    id: "billing",
    href: "/admin/billing",
    label: "Abbonamento & Fatturazione",
    description: "Piano, quote e gestione della sottoscrizione",
    placement: "settings",
    icon: Activity,
    adminOnly: true,
  },
  {
    id: "pms-config",
    href: "/admin/crm/pms-sync",
    label: "Collegamento gestionale",
    description: "Credenziali e stato della sincronizzazione con il PMS della struttura",
    placement: "settings",
    icon: Database,
    module: "crm",
    area: "crm",
  },
  {
    id: "profile",
    href: "/admin/profile",
    label: "Il Mio Profilo",
    description: "Modifica la tua password e visualizza i tuoi permessi",
    placement: "settings",
    icon: Lock,
  },
  {
    id: "platform-structures",
    href: "/super-admin/structures",
    label: "Strutture",
    description: "Tutti i clienti della piattaforma, con moduli attivi e stato dell'abbonamento",
    placement: "platform",
    icon: Building2,
    platformOnly: true,
    match: (p) => p.startsWith("/super-admin/structures"),
  },
  {
    id: "platform-onboarding",
    href: "/super-admin/onboarding",
    label: "Nuovo cliente",
    description: "Crea una nuova struttura e attiva i moduli acquistati",
    placement: "platform",
    icon: UserPlus,
    platformOnly: true,
  },
  {
    id: "platform-collaborators",
    href: "/super-admin/collaborators",
    label: "Collaboratori",
    description: "Chi lavora sulla piattaforma, con i relativi permessi",
    placement: "platform",
    icon: Users,
    platformOnly: true,
  },
  {
    id: "platform-billing",
    href: "/super-admin/billing",
    label: "Fatturazione piattaforma",
    description: "Abbonamenti, ricavi ricorrenti e pagamenti di tutti i clienti",
    placement: "platform",
    icon: CreditCard,
    platformOnly: true,
  },
  {
    id: "platform-module-costs",
    href: "/super-admin/module-costs",
    label: "Costi e prezzi dei moduli",
    description: "Quanto costa e a quanto si vende ogni modulo, per struttura",
    placement: "platform",
    icon: Coins,
    platformOnly: true,
  },
  {
    id: "platform-roadmap",
    href: "/super-admin/roadmap",
    label: "Roadmap",
    description: "Stato di avanzamento dei moduli della suite",
    placement: "platform",
    icon: ListTodo,
    platformOnly: true,
  },
  {
    id: "platform-settings",
    href: "/super-admin/settings",
    label: "Impostazioni piattaforma",
    description: "Configurazione trasversale della piattaforma",
    placement: "platform",
    icon: Settings,
    platformOnly: true,
  },
]

export const SETTINGS_ICON = Settings
export const SETTINGS_HUB_HREF = "/admin/settings"
export const OPERATIVE_ENTRIES: NavEntry[] = NAV_ENTRIES.filter((e) => e.placement === "operative")
export const SETTINGS_ENTRIES: NavEntry[] = NAV_ENTRIES.filter((e) => e.placement === "settings")
export const PLATFORM_ENTRIES: NavEntry[] = NAV_ENTRIES.filter((e) => e.placement === "platform")
export const OPERATIVE_PRIMARY: NavEntry[] = OPERATIVE_ENTRIES.filter((e) => e.primary)
export const OPERATIVE_SECONDARY: NavEntry[] = OPERATIVE_ENTRIES.filter((e) => !e.primary)

export interface NavViewer {
  isAdmin?: boolean
  isPlatformAdmin?: boolean
  areas?: string[]
  activeModules?: string[] | null
  canManageUsers?: boolean
}

export function visibleEntries(entries: NavEntry[], viewer: NavViewer): NavEntry[] {
  const { isAdmin, isPlatformAdmin, areas, activeModules, canManageUsers } = viewer
  const active = activeModules ? new Set(activeModules) : null
  const granted = new Set(areas ?? [])

  return entries.filter((entry) => {
    if (entry.strictModule && (!active || !entry.module || !active.has(entry.module))) return false
    if (entry.module && active && !active.has(entry.module)) return false
    if (entry.platformOnly && !isPlatformAdmin) return false
    if (isAdmin) return true
    if (entry.adminOnly) return false
    if (entry.requiresPermission === "can_manage_users" && !canManageUsers) return false
    if (entry.area && !granted.has(entry.area)) return false
    return true
  })
}
