"use client"
import {useCallback,useEffect,useMemo,useState} from "react"
import {addDays,format,startOfWeek} from "date-fns"
import {it} from "date-fns/locale"
import {CalendarClock,Plus,Send,Users} from "lucide-react"
import {AdminHeader} from "@/components/admin/admin-header"
import {Button} from "@/components/ui/button"
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card"
import {Input} from "@/components/ui/input"
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select"
import {Badge} from "@/components/ui/badge"
type Department={id:string;name:string;color:string};type Employee={id:string;first_name:string;last_name:string;email:string|null;department_id:string|null};type Shift={id:string;employee_id:string;starts_at:string;ends_at:string;status:"draft"|"published";response_status:string};type Leave={id:string;employee_id:string;kind:string;starts_on:string;ends_on:string;status:string}
const today=()=>format(new Date(),"yyyy-MM-dd")
export default function Page(){const[week,setWeek]=useState(startOfWeek(new Date(),{weekStartsOn:1}));const[departments,setDepartments]=useState<Department[]>([]);const[employees,setEmployees]=useState<Employee[]>([]);const[shifts,setShifts]=useState<Shift[]>([]);const[leaves,setLeaves]=useState<Leave[]>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[department,setDepartment]=useState("");const[employee,setEmployee]=useState({first_name:"",last_name:"",email:"",department_id:"none",weekly_hours:"40",job_title:"",telegram_chat_id:""});const[shift,setShift]=useState({employee_id:"",date:today(),starts:"07:30",ends:"15:00",break_minutes:"0"});const[leave,setLeave]=useState({employee_id:"",kind:"holiday",starts_on:today(),ends_on:today(),reason:""});
const load=useCallback(async()=>{const r=await fetch(`/api/admin/hr?from=${format(week,"yyyy-MM-dd")}`),d=await r.json();if(!r.ok)throw new Error(d.error);setDepartments(d.departments);setEmployees(d.employees);setShifts(d.shifts);setLeaves(d.leave_requests)},[week]);useEffect(()=>{load().catch(()=>setMessage("Applica prima la migrazione HR al database."))},[load]);
async function post(body:object){setBusy(true);setMessage("");try{const r=await fetch("/api/admin/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error==="shift_overlap"?"Turno sovrapposto per questo dipendente.":d.error);await load();setMessage("Salvato.");return true}catch(e){setMessage(e instanceof Error?e.message:"Errore");return false}finally{setBusy(false)}}
const name=(id:string)=>{const e=employees.find(x=>x.id===id);return e?`${e.first_name} ${e.last_name}`:"Dipendente"};const drafts=shifts.filter(x=>x.status==="draft").map(x=>x.id);const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(week,i)),[week]);
return <div className="min-h-screen bg-background"><AdminHeader title="HotelAccelerator HR" subtitle="Dipendenti, turni, notifiche e assenze"/><main className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-8">{message&&<div className="rounded-lg border px-4 py-3 text-sm">{message}</div>}
<div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Dipendenti</CardDescription><CardTitle className="flex gap-2"><Users/>{employees.length}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Turni settimana</CardDescription><CardTitle className="flex gap-2"><CalendarClock/>{shifts.length}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Richieste assenza aperte</CardDescription><CardTitle>{leaves.filter(x=>x.status==="pending").length}</CardTitle></CardHeader></Card></div>
<div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Reparti e dipendenti</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input placeholder="Nuovo reparto" value={department} onChange={e=>setDepartment(e.target.value)}/><Button disabled={busy||department.length<2} onClick={async()=>{if(await post({action:"department",name:department}))setDepartment("")}}><Plus/></Button></div><div className="grid gap-2 sm:grid-cols-2"><Input placeholder="Nome" value={employee.first_name} onChange={e=>setEmployee({...employee,first_name:e.target.value})}/><Input placeholder="Cognome" value={employee.last_name} onChange={e=>setEmployee({...employee,last_name:e.target.value})}/><Input type="email" placeholder="Email" value={employee.email} onChange={e=>setEmployee({...employee,email:e.target.value})}/><Select value={employee.department_id} onValueChange={v=>setEmployee({...employee,department_id:v})}><SelectTrigger><SelectValue placeholder="Reparto"/></SelectTrigger><SelectContent><SelectItem value="none">Nessun reparto</SelectItem>{departments.map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select><Input placeholder="Chat ID Telegram (opzionale)" value={employee.telegram_chat_id} onChange={e=>setEmployee({...employee,telegram_chat_id:e.target.value})}/><Button disabled={busy||!employee.first_name||!employee.last_name} onClick={async()=>{if(await post({action:"employee",...employee,department_id:employee.department_id==="none"?null:employee.department_id}))setEmployee({...employee,first_name:"",last_name:"",email:"",telegram_chat_id:""})}}>Aggiungi dipendente</Button></div></CardContent></Card>
<Card><CardHeader><CardTitle className="text-base">Ferie, permessi e indisponibilità</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={leave.employee_id} onValueChange={v=>setLeave({...leave,employee_id:v})}><SelectTrigger><SelectValue placeholder="Dipendente"/></SelectTrigger><SelectContent>{employees.map(x=><SelectItem key={x.id} value={x.id}>{name(x.id)}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-3 gap-2"><Select value={leave.kind} onValueChange={v=>setLeave({...leave,kind:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="holiday">Ferie</SelectItem><SelectItem value="permission">Permesso</SelectItem><SelectItem value="rol">ROL</SelectItem><SelectItem value="sickness">Malattia</SelectItem><SelectItem value="unavailability">Indisponibilità</SelectItem></SelectContent></Select><Input type="date" value={leave.starts_on} onChange={e=>setLeave({...leave,starts_on:e.target.value})}/><Input type="date" value={leave.ends_on} onChange={e=>setLeave({...leave,ends_on:e.target.value})}/></div><Button disabled={busy||!leave.employee_id} onClick={()=>post({action:"leave",...leave})}>Inserisci richiesta</Button><div className="space-y-2">{leaves.filter(x=>x.status==="pending").map(x=><div key={x.id} className="flex items-center justify-between rounded border p-2 text-sm"><span>{name(x.employee_id)} · {x.starts_on}–{x.ends_on}</span><div className="flex gap-1"><Button size="sm" onClick={()=>post({action:"review_leave",request_id:x.id,decision:"approved"})}>Approva</Button><Button size="sm" variant="outline" onClick={()=>post({action:"review_leave",request_id:x.id,decision:"rejected"})}>Rifiuta</Button></div></div>)}</div></CardContent></Card></div>
<Card><CardHeader><CardTitle className="text-base">Nuovo turno</CardTitle><CardDescription>I turni notturni possono terminare il giorno successivo.</CardDescription></CardHeader><CardContent className="grid gap-2 md:grid-cols-6"><Select value={shift.employee_id} onValueChange={v=>setShift({...shift,employee_id:v})}><SelectTrigger><SelectValue placeholder="Dipendente"/></SelectTrigger><SelectContent>{employees.map(x=><SelectItem key={x.id} value={x.id}>{name(x.id)}</SelectItem>)}</SelectContent></Select><Input type="date" value={shift.date} onChange={e=>setShift({...shift,date:e.target.value})}/><Input type="time" value={shift.starts} onChange={e=>setShift({...shift,starts:e.target.value})}/><Input type="time" value={shift.ends} onChange={e=>setShift({...shift,ends:e.target.value})}/><Input type="number" placeholder="Pausa minuti" value={shift.break_minutes} onChange={e=>setShift({...shift,break_minutes:e.target.value})}/><Button disabled={busy||!shift.employee_id} onClick={()=>post({action:"shift",...shift})}><Plus className="mr-1"/>Crea bozza</Button></CardContent></Card>
<Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Settimana</CardTitle><CardDescription>{format(week,"d MMM",{locale:it})}–{format(addDays(week,6),"d MMM yyyy",{locale:it})}</CardDescription></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setWeek(addDays(week,-7))}>‹</Button><Button variant="outline" onClick={()=>setWeek(addDays(week,7))}>›</Button><Button disabled={!drafts.length||busy} onClick={()=>post({action:"publish",shift_ids:drafts})}><Send className="mr-2"/>Pubblica e notifica ({drafts.length})</Button></div></CardHeader><CardContent className="grid gap-2 md:grid-cols-7">{days.map(day=><div key={day.toISOString()} className="min-h-40 rounded border p-2"><b className="text-sm capitalize">{format(day,"EEE d",{locale:it})}</b>{shifts.filter(x=>format(new Date(x.starts_at),"yyyy-MM-dd")===format(day,"yyyy-MM-dd")).map(x=><div key={x.id} className="mt-2 rounded bg-muted p-2 text-xs"><b>{name(x.employee_id)}</b><div>{format(new Date(x.starts_at),"HH:mm")}–{format(new Date(x.ends_at),"HH:mm")}</div><Badge variant={x.status==="draft"?"outline":"default"}>{x.status==="draft"?"Bozza":x.response_status==="confirmed"?"Confermato":"Pubblicato"}</Badge></div>)}</div>)}</CardContent></Card>
</main></div>}
