-- Area Assistenza + Customer Success del CRM Super Admin 4BID.
-- Queste entita' appartengono alla piattaforma e non al CRM dei tenant.

create table if not exists public.platform_support_cases (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated by default as identity unique,
  customer_account_id uuid not null references public.customer_accounts(id) on delete cascade,
  product_key text
    check (product_key is null or product_key in ('hotelaccelerator','santaddeo','hotelprofitai','manubot')),
  title text not null,
  description text,
  case_type text not null default 'other'
    check (case_type in ('bug','configuration','training','administration','billing','integration','feature_request','commercial','other')),
  priority text not null default 'normal'
    check (priority in ('low','normal','high','critical')),
  status text not null default 'new'
    check (status in ('new','assigned','waiting_customer','in_progress','resolved','closed')),
  channel text not null default 'manual'
    check (channel in ('manual','email','phone','chat','whatsapp','federated')),
  assignee_label text,
  team_label text,
  sla_first_response_due_at timestamptz,
  sla_resolution_due_at timestamptz,
  first_responded_at timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,
  last_customer_activity_at timestamptz,
  last_agent_activity_at timestamptz,
  source_conversation_id uuid,
  source_external_ref text,
  github_issue_url text,
  tags text[] not null default '{}'::text[],
  metadata jsonb not null default '{}'::jsonb,
  created_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists platform_support_cases_customer_idx
  on public.platform_support_cases(customer_account_id, created_at desc);
create index if not exists platform_support_cases_queue_idx
  on public.platform_support_cases(status, priority, created_at desc);
create index if not exists platform_support_cases_first_sla_idx
  on public.platform_support_cases(sla_first_response_due_at)
  where first_responded_at is null and status not in ('resolved','closed');
create index if not exists platform_support_cases_resolution_sla_idx
  on public.platform_support_cases(sla_resolution_due_at)
  where resolved_at is null and status <> 'closed';
create unique index if not exists platform_support_cases_source_ref_key
  on public.platform_support_cases(source_external_ref)
  where source_external_ref is not null;

comment on column public.platform_support_cases.source_conversation_id is
  'Conversation UUID when the case originates from the 4BID Inbox/support federation. Intentionally no FK so federation can remain loosely coupled.';

create table if not exists public.platform_customer_success_actions (
  id uuid primary key default gen_random_uuid(),
  customer_account_id uuid not null references public.customer_accounts(id) on delete cascade,
  product_key text
    check (product_key is null or product_key in ('hotelaccelerator','santaddeo','hotelprofitai','manubot')),
  action_type text not null default 'check_in'
    check (action_type in ('onboarding','adoption','health_recovery','renewal','upsell','check_in','training','other')),
  title text not null,
  notes text,
  priority text not null default 'normal'
    check (priority in ('low','normal','high','critical')),
  status text not null default 'open'
    check (status in ('open','done','cancelled')),
  due_at timestamptz,
  owner_label text,
  completed_at timestamptz,
  created_by_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists platform_customer_success_actions_customer_idx
  on public.platform_customer_success_actions(customer_account_id, created_at desc);
create index if not exists platform_customer_success_actions_open_idx
  on public.platform_customer_success_actions(status, due_at, priority)
  where status = 'open';

alter table public.platform_support_cases enable row level security;
alter table public.platform_customer_success_actions enable row level security;

-- Esattamente come Customer Intelligence: niente accesso diretto dal browser.
-- Le route /api/super-admin/* verificano il ruolo e poi usano service_role.
revoke all on table public.platform_support_cases from public, anon, authenticated;
revoke all on table public.platform_customer_success_actions from public, anon, authenticated;

grant select, insert, update, delete on table public.platform_support_cases to service_role;
grant select, insert, update, delete on table public.platform_customer_success_actions to service_role;
