-- A staff handoff is a durable workflow, not a sentence generated by an LLM.
-- It is intentionally server-only: public widget visitors can create it only
-- through the tenant-scoped API route, which resolves the widget public key.
create table if not exists public.conversation_staff_handoffs (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  channel text not null check (channel in ('chat', 'whatsapp', 'telegram', 'email')),
  status text not null default 'collecting' check (status in ('collecting', 'registered', 'cancelled')),
  original_question text not null check (length(btrim(original_question)) between 1 and 1500),
  contact_first_name text,
  contact_last_name text,
  contact_email text,
  contact_phone text,
  todo_id uuid references public.todos(id) on delete set null,
  manubot_task_id text,
  requested_at timestamptz not null default now(),
  registered_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversation_staff_handoffs_property_conversation_key unique (property_id, conversation_id)
);

create index if not exists conversation_staff_handoffs_property_status_requested_idx
  on public.conversation_staff_handoffs (property_id, status, requested_at desc);

alter table public.conversation_staff_handoffs enable row level security;

-- The table contains contact data and is used only by server routes with the
-- service key. Do not make it available through the Data API to browser roles.
revoke all privileges on table public.conversation_staff_handoffs from anon, authenticated;
grant select, insert, update on table public.conversation_staff_handoffs to service_role;

drop policy if exists "backend_only_deny" on public.conversation_staff_handoffs;
create policy "backend_only_deny"
  on public.conversation_staff_handoffs
  as restrictive
  for all
  to anon, authenticated
  using (false)
  with check (false);
